const db = require("./connection");
const { Card } = require("../models");
const cleanDB = require("./cleanDB");

db.once("open", async () => {
  await cleanDB("Card", "cards");

  const cards = await Card.insertMany([
    { name: "ar00", val: 0 },
    { name: "ar01", val: 1 },
    { name: "ar02", val: 2 },
    { name: "ar03", val: 3 },
    { name: "ar04", val: 4 },
    { name: "ar05", val: 5 },
    { name: "ar06", val: 6 },
    { name: "ar07", val: 7 },
    { name: "ar08", val: 8 },
    { name: "ar09", val: 9 },
    { name: "ar10", val: 10 },
    { name: "ar11", val: 11 },
    { name: "ar12", val: 12 },
    { name: "ar13", val: 13 },
    { name: "ar14", val: 14 },
    { name: "ar15", val: 15 },
    { name: "ar16", val: 16 },
    { name: "ar17", val: 17 },
    { name: "ar18", val: 18 },
    { name: "ar19", val: 19 },
    { name: "ar20", val: 20 },
    { name: "ar21", val: 21 },
    { name: "cuac", val: 22 },
    { name: "cu02", val: 23 },
    { name: "cu03", val: 24 },
    { name: "cu04", val: 25 },
    { name: "cu05", val: 26 },
    { name: "cu06", val: 27 },
    { name: "cu07", val: 28 },
    { name: "cu08", val: 29 },
    { name: "cu09", val: 30 },
    { name: "cu10", val: 31 },
    { name: "cuki", val: 32 },
    { name: "cuqu", val: 33 },
    { name: "cukn", val: 34 },
    { name: "cupa", val: 35 },
    { name: "swac", val: 36 },
    { name: "sw02", val: 37 },
    { name: "sw03", val: 38 },
    { name: "sw04", val: 39 },
    { name: "sw05", val: 40 },
    { name: "sw06", val: 41 },
    { name: "sw07", val: 42 },
    { name: "sw08", val: 43 },
    { name: "sw09", val: 44 },
    { name: "sw10", val: 45 },
    { name: "swki", val: 46 },
    { name: "swqu", val: 47 },
    { name: "swkn", val: 48 },
    { name: "swpa", val: 49 },
    { name: "peac", val: 50 },
    { name: "pe02", val: 51 },
    { name: "pe03", val: 52 },
    { name: "pe04", val: 53 },
    { name: "pe05", val: 54 },
    { name: "pe06", val: 55 },
    { name: "pe07", val: 56 },
    { name: "pe08", val: 57 },
    { name: "pe09", val: 58 },
    { name: "pe10", val: 59 },
    { name: "peki", val: 60 },
    { name: "pequ", val: 61 },
    { name: "pekn", val: 62 },
    { name: "pepa", val: 63 },
    { name: "waac", val: 64 },
    { name: "wa02", val: 65 },
    { name: "wa03", val: 66 },
    { name: "wa04", val: 67 },
    { name: "wa05", val: 68 },
    { name: "wa06", val: 69 },
    { name: "wa07", val: 70 },
    { name: "wa08", val: 71 },
    { name: "wa09", val: 72 },
    { name: "wa10", val: 73 },
    { name: "waki", val: 74 },
    { name: "waqu", val: 75 },
    { name: "wakn", val: 76 },
    { name: "wapa", val: 77 },
  ]);

  console.log("cards seeded");

  process.exit();
});
