const db = require("./connection");
const { Card } = require('../models');
const cleanDB = require('./cleanDB');

db.once("open", async () => {
  await cleanDB("Card", "cards");

  const cards = await Card.insertMany([
    { name: "ar00" },
    { name: "ar01" },
    { name: "ar02" },
    { name: "ar03" },
    { name: "ar04" },
    { name: "ar05" },
    { name: "ar06" },
    { name: "ar07" },
    { name: "ar08" },
    { name: "ar09" },
    { name: "ar10" },
    { name: "ar11" },
    { name: "ar12" },
    { name: "ar13" },
    { name: "ar14" },
    { name: "ar15" },
    { name: "ar16" },
    { name: "ar17" },
    { name: "ar18" },
    { name: "ar19" },
    { name: "ar20" },
    { name: "ar21" },
    { name: "cuac" },
    { name: "cu02" },
    { name: "cu03" },
    { name: "cu04" },
    { name: "cu05" },
    { name: "cu06" },
    { name: "cu07" },
    { name: "cu08" },
    { name: "cu09" },
    { name: "cu10" },
    { name: "cuki" },
    { name: "cuqu" },
    { name: "cukn" },
    { name: "cupa" },
    { name: "swac" },
    { name: "sw02" },
    { name: "sw03" },
    { name: "sw04" },
    { name: "sw05" },
    { name: "sw06" },
    { name: "sw07" },
    { name: "sw08" },
    { name: "sw09" },
    { name: "sw10" },
    { name: "swki" },
    { name: "swqu" },
    { name: "swkn" },
    { name: "swpa" },
    { name: "peac" },
    { name: "pe02" },
    { name: "pe03" },
    { name: "pe04" },
    { name: "pe05" },
    { name: "pe06" },
    { name: "pe07" },
    { name: "pe08" },
    { name: "pe09" },
    { name: "pe10" },
    { name: "peki" },
    { name: "pequ" },
    { name: "pekn" },
    { name: "pepa" },
    { name: "waac" },
    { name: "wa02" },
    { name: "wa03" },
    { name: "wa04" },
    { name: "wa05" },
    { name: "wa06" },
    { name: "wa07" },
    { name: "wa08" },
    { name: "wa09" },
    { name: "wa10" },
    { name: "waki" },
    { name: "waqu" },
    { name: "wakn" },
    { name: "wapa" },
  ]);

  console.log('cards seeded');

  process.exit();
});